In [1]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq

In [2]:
dataset_dir = 'child-mind-institute-problematic-internet-use/'
train_meta_file = 'train.csv'
test_meta_file = 'test.csv'
example_file = 'series_train.parquet/id=0a431608/part-0.parquet'

In [3]:
train_meta = pd.read_csv(dataset_dir + train_meta_file)
display(train_meta)

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,ff8a2de4,Fall,13,0,Spring,60.0,Fall,16.362460,59.5,82.4,...,1.0,1.0,0.0,32.0,Winter,35.0,50.0,Fall,1.0,1.0
3956,ffa9794a,Winter,10,0,NaN,NaN,Spring,18.764678,53.5,76.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winter,0.0,NaN
3957,ffcd4dbd,Fall,11,0,Spring,68.0,Winter,21.441500,60.0,109.8,...,1.0,0.0,1.0,31.0,Winter,56.0,77.0,Fall,0.0,1.0
3958,ffed1dd5,Spring,13,0,Spring,70.0,Winter,12.235895,70.7,87.0,...,1.0,1.0,1.0,19.0,Spring,33.0,47.0,Spring,1.0,0.0
3959,ffef538e,Spring,11,0,NaN,NaN,Winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring,1.0,NaN

In [6]:
train_meta.isnull().sum()

id                                           0
Basic_Demos-Enroll_Season                    0
Basic_Demos-Age                              0
Basic_Demos-Sex                              0
CGAS-Season                               1405
                                          ...
SDS-SDS_Total_Raw                         1351
SDS-SDS_Total_T                           1354
PreInt_EduHx-Season                        420
PreInt_EduHx-computerinternet_hoursday     659
sii                                       1224
Length: 82, dtype: int64

In [ ]:
pd.

This is how you are supposed to read `.parquet` files

In [4]:
pq.read_table(source=dataset_dir + example_file).to_pandas()

,step,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT,id
0,0,0.261824,0.557185,-0.241188,0.021901,-14.491111,0.0,0.500000,4190.000000,58080000000000,5,3,7.0,0a431608
1,1,0.384026,0.588780,-0.228588,0.015988,-15.907443,0.0,2.333333,4190.083496,58085000000000,5,3,7.0,0a431608
2,2,0.090461,0.496018,-0.713676,0.071832,-51.262962,0.0,4.600000,4190.166504,58090000000000,5,3,7.0,0a431608
3,3,-0.189618,0.721723,-0.229030,0.041824,-13.912786,0.0,1.500000,4190.250000,58095000000000,5,3,7.0,0a431608
4,4,-0.542998,0.199625,-0.130518,0.055110,-14.132037,0.0,47.500000,4190.333496,58100000000000,5,3,7.0,0a431608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258649,258649,-0.959830,-0.178453,-0.140619,0.000000,-8.176014,0.0,10.600000,3778.583252,6515000000000,1,3,31.0,0a431608
258650,258650,-0.960479,-0.180191,-0.138563,0.000000,-7.994138,0.0,10.600000,3778.666748,6520000000000,1,3,31.0,0a431608
258651,258651,0.119225,-0.800576,0.308204,0.037640,17.917601,0.0,10.600000,3778.750000,6645000000000,1,3,31.0,0a431608
258652,258652,0.141519,-0.781951,0.616236,0.005807,37.774498,0.0,10.600000,3778.833252,6650000000000,1,3,31.0,0a431608
258653,258653,0.141701,-0.776426,0.624417,0.006507,38.273067,0.0,10.600000,3778.916748,6655000000000,1,3,31.0,0a431608